# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 687)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_Menu = QtWidgets.QGridLayout()
        self.gridLayout_Menu.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_Menu.setObjectName("gridLayout_Menu")
        self.pushButton_action_open_data = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_action_open_data.sizePolicy().hasHeightForWidth())
        self.pushButton_action_open_data.setSizePolicy(sizePolicy)
        self.pushButton_action_open_data.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_action_open_data.setIcon(icon)
        self.pushButton_action_open_data.setObjectName("pushButton_action_open_data")
        self.gridLayout_Menu.addWidget(self.pushButton_action_open_data, 0, 0, 1, 1)
        self.Clustering = QtWidgets.QGroupBox(self.centralwidget)
        self.Clustering.setMinimumSize(QtCore.QSize(0, 65))
        self.Clustering.setMaximumSize(QtCore.QSize(16777215, 65))
        self.Clustering.setObjectName("Clustering")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Clustering)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_k_means = QtWidgets.QPushButton(self.Clustering)
        self.pushButton_k_means.setEnabled(False)
        self.pushButton_k_means.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/kmean.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_k_means.setIcon(icon1)
        self.pushButton_k_means.setObjectName("pushButton_k_means")
        self.horizontalLayout_6.addWidget(self.pushButton_k_means)
        self.pushButton_action_affinity_propagation = QtWidgets.QPushButton(self.Clustering)
        self.pushButton_action_affinity_propagation.setEnabled(False)
        self.pushButton_action_affinity_propagation.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/affinity.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_action_affinity_propagation.setIcon(icon2)
        self.pushButton_action_affinity_propagation.setObjectName("pushButton_action_affinity_propagation")
        self.horizontalLayout_6.addWidget(self.pushButton_action_affinity_propagation)
        self.pushButton_action_mean_shift = QtWidgets.QPushButton(self.Clustering)
        self.pushButton_action_mean_shift.setEnabled(False)
        self.pushButton_action_mean_shift.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/mean-shift.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_action_mean_shift.setIcon(icon3)
        self.pushButton_action_mean_shift.setObjectName("pushButton_action_mean_shift")
        self.horizontalLayout_6.addWidget(self.pushButton_action_mean_shift)
        self.pushButton_action_spectral_clustering = QtWidgets.QPushButton(self.Clustering)
        self.pushButton_action_spectral_clustering.setEnabled(False)
        self.pushButton_action_spectral_clustering.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/spectral-clustering.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_action_spectral_clustering.setIcon(icon4)
        self.pushButton_action_spectral_clustering.setObjectName("pushButton_action_spectral_clustering")
        self.horizontalLayout_6.addWidget(self.pushButton_action_spectral_clustering)
        self.pushButton_action_hierarcical_clustering = QtWidgets.QPushButton(self.Clustering)
        self.pushButton_action_hierarcical_clustering.setEnabled(False)
        self.pushButton_action_hierarcical_clustering.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/hierarchical.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_action_hierarcical_clustering.setIcon(icon5)
        self.pushButton_action_hierarcical_clustering.setObjectName("pushButton_action_hierarcical_clustering")
        self.horizontalLayout_6.addWidget(self.pushButton_action_hierarcical_clustering)
        self.pushButton_action_DBSCAN = QtWidgets.QPushButton(self.Clustering)
        self.pushButton_action_DBSCAN.setEnabled(False)
        self.pushButton_action_DBSCAN.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/dbscan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_action_DBSCAN.setIcon(icon6)
        self.pushButton_action_DBSCAN.setObjectName("pushButton_action_DBSCAN")
        self.horizontalLayout_6.addWidget(self.pushButton_action_DBSCAN)
        self.gridLayout_Menu.addWidget(self.Clustering, 0, 4, 1, 1)
        self.Final_Solution = QtWidgets.QGroupBox(self.centralwidget)
        self.Final_Solution.setMinimumSize(QtCore.QSize(0, 65))
        self.Final_Solution.setMaximumSize(QtCore.QSize(16777215, 65))
        self.Final_Solution.setObjectName("Final_Solution")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Final_Solution)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_action_save_final_solution = QtWidgets.QPushButton(self.Final_Solution)
        self.pushButton_action_save_final_solution.setEnabled(False)
        self.pushButton_action_save_final_solution.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/save_final.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_action_save_final_solution.setIcon(icon7)
        self.pushButton_action_save_final_solution.setObjectName("pushButton_action_save_final_solution")
        self.horizontalLayout_3.addWidget(self.pushButton_action_save_final_solution)
        self.pushButton_action_export_as_final_solution = QtWidgets.QPushButton(self.Final_Solution)
        self.pushButton_action_export_as_final_solution.setEnabled(False)
        self.pushButton_action_export_as_final_solution.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/jpg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_action_export_as_final_solution.setIcon(icon8)
        self.pushButton_action_export_as_final_solution.setObjectName("pushButton_action_export_as_final_solution")
        self.horizontalLayout_3.addWidget(self.pushButton_action_export_as_final_solution)
        self.pushButton_action_clear_final_solution = QtWidgets.QPushButton(self.Final_Solution)
        self.pushButton_action_clear_final_solution.setEnabled(False)
        self.pushButton_action_clear_final_solution.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_action_clear_final_solution.setIcon(icon9)
        self.pushButton_action_clear_final_solution.setObjectName("pushButton_action_clear_final_solution")
        self.horizontalLayout_3.addWidget(self.pushButton_action_clear_final_solution)
        self.pushButton_action_undo_final_solution = QtWidgets.QPushButton(self.Final_Solution)
        self.pushButton_action_undo_final_solution.setEnabled(False)
        self.pushButton_action_undo_final_solution.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_action_undo_final_solution.setIcon(icon10)
        self.pushButton_action_undo_final_solution.setObjectName("pushButton_action_undo_final_solution")
        self.horizontalLayout_3.addWidget(self.pushButton_action_undo_final_solution)
        self.pushButton_action_redo_final_solution = QtWidgets.QPushButton(self.Final_Solution)
        self.pushButton_action_redo_final_solution.setEnabled(False)
        self.pushButton_action_redo_final_solution.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_action_redo_final_solution.setIcon(icon11)
        self.pushButton_action_redo_final_solution.setObjectName("pushButton_action_redo_final_solution")
        self.horizontalLayout_3.addWidget(self.pushButton_action_redo_final_solution)
        self.gridLayout_Menu.addWidget(self.Final_Solution, 0, 3, 1, 1)
        self.Heuristic = QtWidgets.QGroupBox(self.centralwidget)
        self.Heuristic.setMinimumSize(QtCore.QSize(0, 65))
        self.Heuristic.setMaximumSize(QtCore.QSize(16777215, 65))
        self.Heuristic.setObjectName("Heuristic")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Heuristic)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_action_hill_climbing = QtWidgets.QPushButton(self.Heuristic)
        self.pushButton_action_hill_climbing.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_action_hill_climbing.sizePolicy().hasHeightForWidth())
        self.pushButton_action_hill_climbing.setSizePolicy(sizePolicy)
        self.pushButton_action_hill_climbing.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/hillclimb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_action_hill_climbing.setIcon(icon12)
        self.pushButton_action_hill_climbing.setObjectName("pushButton_action_hill_climbing")
        self.horizontalLayout_4.addWidget(self.pushButton_action_hill_climbing)
        self.pushButton_action_simulated_anneling = QtWidgets.QPushButton(self.Heuristic)
        self.pushButton_action_simulated_anneling.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_action_simulated_anneling.sizePolicy().hasHeightForWidth())
        self.pushButton_action_simulated_anneling.setSizePolicy(sizePolicy)
        self.pushButton_action_simulated_anneling.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/simulated-anneling.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_action_simulated_anneling.setIcon(icon13)
        self.pushButton_action_simulated_anneling.setObjectName("pushButton_action_simulated_anneling")
        self.horizontalLayout_4.addWidget(self.pushButton_action_simulated_anneling)
        self.gridLayout_Menu.addWidget(self.Heuristic, 0, 5, 1, 1)
        self.Initial_Solution = QtWidgets.QGroupBox(self.centralwidget)
        self.Initial_Solution.setMinimumSize(QtCore.QSize(65, 0))
        self.Initial_Solution.setMaximumSize(QtCore.QSize(16777215, 65))
        self.Initial_Solution.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Initial_Solution.setObjectName("Initial_Solution")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Initial_Solution)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_action_save_initial_solution = QtWidgets.QPushButton(self.Initial_Solution)
        self.pushButton_action_save_initial_solution.setEnabled(False)
        self.pushButton_action_save_initial_solution.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/save_initial.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_action_save_initial_solution.setIcon(icon14)
        self.pushButton_action_save_initial_solution.setObjectName("pushButton_action_save_initial_solution")
        self.horizontalLayout.addWidget(self.pushButton_action_save_initial_solution)
        self.pushButton_action_export_as_initial_solution = QtWidgets.QPushButton(self.Initial_Solution)
        self.pushButton_action_export_as_initial_solution.setEnabled(False)
        self.pushButton_action_export_as_initial_solution.setText("")
        self.pushButton_action_export_as_initial_solution.setIcon(icon8)
        self.pushButton_action_export_as_initial_solution.setObjectName("pushButton_action_export_as_initial_solution")
        self.horizontalLayout.addWidget(self.pushButton_action_export_as_initial_solution)
        self.pushButton_action_clear_initial_solution = QtWidgets.QPushButton(self.Initial_Solution)
        self.pushButton_action_clear_initial_solution.setEnabled(False)
        self.pushButton_action_clear_initial_solution.setText("")
        self.pushButton_action_clear_initial_solution.setIcon(icon9)
        self.pushButton_action_clear_initial_solution.setObjectName("pushButton_action_clear_initial_solution")
        self.horizontalLayout.addWidget(self.pushButton_action_clear_initial_solution)
        self.pushButton_action_undo_initial_solution = QtWidgets.QPushButton(self.Initial_Solution)
        self.pushButton_action_undo_initial_solution.setEnabled(False)
        self.pushButton_action_undo_initial_solution.setText("")
        self.pushButton_action_undo_initial_solution.setIcon(icon10)
        self.pushButton_action_undo_initial_solution.setObjectName("pushButton_action_undo_initial_solution")
        self.horizontalLayout.addWidget(self.pushButton_action_undo_initial_solution)
        self.pushButton_action_redo_initial_solution = QtWidgets.QPushButton(self.Initial_Solution)
        self.pushButton_action_redo_initial_solution.setEnabled(False)
        self.pushButton_action_redo_initial_solution.setText("")
        self.pushButton_action_redo_initial_solution.setIcon(icon11)
        self.pushButton_action_redo_initial_solution.setObjectName("pushButton_action_redo_initial_solution")
        self.horizontalLayout.addWidget(self.pushButton_action_redo_initial_solution)
        self.gridLayout_Menu.addWidget(self.Initial_Solution, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_Menu, 0, 0, 1, 1)
        self.groupBox_manual_solutions = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_manual_solutions.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_manual_solutions.setObjectName("groupBox_manual_solutions")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_manual_solutions)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_manual_solutions = QtWidgets.QVBoxLayout()
        self.verticalLayout_manual_solutions.setObjectName("verticalLayout_manual_solutions")
        self.verticalLayout_hubs = QtWidgets.QVBoxLayout()
        self.verticalLayout_hubs.setObjectName("verticalLayout_hubs")
        self.label_hubs = QtWidgets.QLabel(self.groupBox_manual_solutions)
        self.label_hubs.setObjectName("label_hubs")
        self.verticalLayout_hubs.addWidget(self.label_hubs)
        self.textEdit_hubs = QtWidgets.QTextEdit(self.groupBox_manual_solutions)
        self.textEdit_hubs.setMaximumSize(QtCore.QSize(250, 61))
        self.textEdit_hubs.setObjectName("textEdit_hubs")
        self.verticalLayout_hubs.addWidget(self.textEdit_hubs)
        self.verticalLayout_manual_solutions.addLayout(self.verticalLayout_hubs)
        self.verticalLayout_nodes = QtWidgets.QVBoxLayout()
        self.verticalLayout_nodes.setObjectName("verticalLayout_nodes")
        self.label_nodes = QtWidgets.QLabel(self.groupBox_manual_solutions)
        self.label_nodes.setObjectName("label_nodes")
        self.verticalLayout_nodes.addWidget(self.label_nodes)
        self.textEdit_nodes = QtWidgets.QTextEdit(self.groupBox_manual_solutions)
        self.textEdit_nodes.setMaximumSize(QtCore.QSize(250, 200))
        self.textEdit_nodes.setObjectName("textEdit_nodes")
        self.verticalLayout_nodes.addWidget(self.textEdit_nodes)
        self.verticalLayout_manual_solutions.addLayout(self.verticalLayout_nodes)
        self.pushButton_run = QtWidgets.QPushButton(self.groupBox_manual_solutions)
        self.pushButton_run.setObjectName("pushButton_run")
        self.verticalLayout_manual_solutions.addWidget(self.pushButton_run)
        self.gridLayout_6.addLayout(self.verticalLayout_manual_solutions, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_manual_solutions, 0, 1, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_initial_solution = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_initial_solution.setMinimumSize(QtCore.QSize(360, 360))
        self.groupBox_initial_solution.setObjectName("groupBox_initial_solution")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_initial_solution)
        self.gridLayout.setObjectName("gridLayout")
        self.label_initial_solution = QtWidgets.QLabel(self.groupBox_initial_solution)
        self.label_initial_solution.setText("")
        self.label_initial_solution.setPixmap(QtGui.QPixmap(""))
        self.label_initial_solution.setObjectName("label_initial_solution")
        self.gridLayout.addWidget(self.label_initial_solution, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_initial_solution)
        self.groupBox_final_solution = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_final_solution.setMinimumSize(QtCore.QSize(360, 360))
        self.groupBox_final_solution.setObjectName("groupBox_final_solution")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_final_solution)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_final_solution = QtWidgets.QLabel(self.groupBox_final_solution)
        self.label_final_solution.setText("")
        self.label_final_solution.setPixmap(QtGui.QPixmap(""))
        self.label_final_solution.setObjectName("label_final_solution")
        self.gridLayout_4.addWidget(self.label_final_solution, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_final_solution)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 2, 1)
        self.groupBox_result = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_result.setObjectName("groupBox_result")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_result)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_result = QtWidgets.QLabel(self.groupBox_result)
        self.label_result.setMinimumSize(QtCore.QSize(100, 250))
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.gridLayout_5.addWidget(self.label_result, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_result, 2, 1, 2, 1)
        self.groupBox_info_panel = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_info_panel.setMaximumSize(QtCore.QSize(1000, 200))
        self.groupBox_info_panel.setObjectName("groupBox_info_panel")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_info_panel)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEdit_info_panel = QtWidgets.QTextEdit(self.groupBox_info_panel)
        self.textEdit_info_panel.setMaximumSize(QtCore.QSize(1000, 200))
        self.textEdit_info_panel.setObjectName("textEdit_info_panel")
        self.gridLayout_3.addWidget(self.textEdit_info_panel, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_info_panel, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Export_As = QtWidgets.QMenu(self.menuFile)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_Export_As.setIcon(icon15)
        self.menu_Export_As.setObjectName("menu_Export_As")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menu_Clear = QtWidgets.QMenu(self.menuEdit)
        self.menu_Clear.setIcon(icon9)
        self.menu_Clear.setObjectName("menu_Clear")
        self.menuUndo = QtWidgets.QMenu(self.menuEdit)
        self.menuUndo.setObjectName("menuUndo")
        self.menuRedo = QtWidgets.QMenu(self.menuEdit)
        self.menuRedo.setObjectName("menuRedo")
        self.menu_Clustering = QtWidgets.QMenu(self.menubar)
        self.menu_Clustering.setObjectName("menu_Clustering")
        self.menu_Heuristic = QtWidgets.QMenu(self.menubar)
        self.menu_Heuristic.setObjectName("menu_Heuristic")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open_data = QtWidgets.QAction(MainWindow)
        self.action_open_data.setIcon(icon)
        self.action_open_data.setObjectName("action_open_data")
        self.action_save_initial_solution = QtWidgets.QAction(MainWindow)
        self.action_save_initial_solution.setEnabled(False)
        self.action_save_initial_solution.setIcon(icon14)
        self.action_save_initial_solution.setObjectName("action_save_initial_solution")
        self.action_exit = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exit.setIcon(icon16)
        self.action_exit.setObjectName("action_exit")
        self.action_export_as_initial_solution = QtWidgets.QAction(MainWindow)
        self.action_export_as_initial_solution.setEnabled(False)
        self.action_export_as_initial_solution.setIcon(icon8)
        self.action_export_as_initial_solution.setObjectName("action_export_as_initial_solution")
        self.action_export_as_final_solution = QtWidgets.QAction(MainWindow)
        self.action_export_as_final_solution.setEnabled(False)
        self.action_export_as_final_solution.setIcon(icon8)
        self.action_export_as_final_solution.setObjectName("action_export_as_final_solution")
        self.action_clear_initial_solution = QtWidgets.QAction(MainWindow)
        self.action_clear_initial_solution.setEnabled(False)
        self.action_clear_initial_solution.setIcon(icon9)
        self.action_clear_initial_solution.setObjectName("action_clear_initial_solution")
        self.action_clear_final_solution = QtWidgets.QAction(MainWindow)
        self.action_clear_final_solution.setEnabled(False)
        self.action_clear_final_solution.setIcon(icon9)
        self.action_clear_final_solution.setObjectName("action_clear_final_solution")
        self.action_k_means = QtWidgets.QAction(MainWindow)
        self.action_k_means.setEnabled(False)
        self.action_k_means.setIcon(icon1)
        self.action_k_means.setObjectName("action_k_means")
        self.action_affinity_propagation = QtWidgets.QAction(MainWindow)
        self.action_affinity_propagation.setEnabled(False)
        self.action_affinity_propagation.setIcon(icon2)
        self.action_affinity_propagation.setObjectName("action_affinity_propagation")
        self.action_hill_climbing = QtWidgets.QAction(MainWindow)
        self.action_hill_climbing.setEnabled(False)
        self.action_hill_climbing.setIcon(icon12)
        self.action_hill_climbing.setObjectName("action_hill_climbing")
        self.action_simulated_anneling = QtWidgets.QAction(MainWindow)
        self.action_simulated_anneling.setEnabled(False)
        self.action_simulated_anneling.setIcon(icon13)
        self.action_simulated_anneling.setObjectName("action_simulated_anneling")
        self.action_save_final_solution = QtWidgets.QAction(MainWindow)
        self.action_save_final_solution.setEnabled(False)
        self.action_save_final_solution.setIcon(icon7)
        self.action_save_final_solution.setObjectName("action_save_final_solution")
        self.action_undo_initial_solution = QtWidgets.QAction(MainWindow)
        self.action_undo_initial_solution.setEnabled(False)
        self.action_undo_initial_solution.setIcon(icon10)
        self.action_undo_initial_solution.setObjectName("action_undo_initial_solution")
        self.action_undo_final_solution = QtWidgets.QAction(MainWindow)
        self.action_undo_final_solution.setEnabled(False)
        self.action_undo_final_solution.setIcon(icon10)
        self.action_undo_final_solution.setObjectName("action_undo_final_solution")
        self.action_redo_initial_solution = QtWidgets.QAction(MainWindow)
        self.action_redo_initial_solution.setEnabled(False)
        self.action_redo_initial_solution.setIcon(icon11)
        self.action_redo_initial_solution.setObjectName("action_redo_initial_solution")
        self.action_redo_final_solution = QtWidgets.QAction(MainWindow)
        self.action_redo_final_solution.setEnabled(False)
        self.action_redo_final_solution.setIcon(icon11)
        self.action_redo_final_solution.setObjectName("action_redo_final_solution")
        self.action_mean_shift = QtWidgets.QAction(MainWindow)
        self.action_mean_shift.setEnabled(False)
        self.action_mean_shift.setIcon(icon3)
        self.action_mean_shift.setObjectName("action_mean_shift")
        self.action_spectral_clustering = QtWidgets.QAction(MainWindow)
        self.action_spectral_clustering.setEnabled(False)
        self.action_spectral_clustering.setIcon(icon4)
        self.action_spectral_clustering.setObjectName("action_spectral_clustering")
        self.action_hierarcical_clustering = QtWidgets.QAction(MainWindow)
        self.action_hierarcical_clustering.setEnabled(False)
        self.action_hierarcical_clustering.setIcon(icon5)
        self.action_hierarcical_clustering.setObjectName("action_hierarcical_clustering")
        self.action_DBSCAN = QtWidgets.QAction(MainWindow)
        self.action_DBSCAN.setEnabled(False)
        self.action_DBSCAN.setIcon(icon6)
        self.action_DBSCAN.setObjectName("action_DBSCAN")
        self.menu_Export_As.addAction(self.action_export_as_initial_solution)
        self.menu_Export_As.addAction(self.action_export_as_final_solution)
        self.menuFile.addAction(self.action_open_data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_save_initial_solution)
        self.menuFile.addAction(self.action_save_final_solution)
        self.menuFile.addAction(self.menu_Export_As.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_exit)
        self.menu_Clear.addAction(self.action_clear_initial_solution)
        self.menu_Clear.addAction(self.action_clear_final_solution)
        self.menuUndo.addAction(self.action_undo_initial_solution)
        self.menuUndo.addAction(self.action_undo_final_solution)
        self.menuRedo.addAction(self.action_redo_initial_solution)
        self.menuRedo.addAction(self.action_redo_final_solution)
        self.menuEdit.addAction(self.menu_Clear.menuAction())
        self.menuEdit.addAction(self.menuUndo.menuAction())
        self.menuEdit.addAction(self.menuRedo.menuAction())
        self.menu_Clustering.addAction(self.action_k_means)
        self.menu_Clustering.addAction(self.action_affinity_propagation)
        self.menu_Clustering.addAction(self.action_mean_shift)
        self.menu_Clustering.addAction(self.action_spectral_clustering)
        self.menu_Clustering.addAction(self.action_hierarcical_clustering)
        self.menu_Clustering.addAction(self.action_DBSCAN)
        self.menu_Heuristic.addAction(self.action_hill_climbing)
        self.menu_Heuristic.addAction(self.action_simulated_anneling)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menu_Clustering.menuAction())
        self.menubar.addAction(self.menu_Heuristic.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Clustering.setTitle(_translate("MainWindow", "Clustering"))
        self.Final_Solution.setTitle(_translate("MainWindow", "Final Solution"))
        self.Heuristic.setTitle(_translate("MainWindow", "Heuristic"))
        self.Initial_Solution.setTitle(_translate("MainWindow", "Initial Solution"))
        self.groupBox_manual_solutions.setTitle(_translate("MainWindow", "Manual Solutions"))
        self.label_hubs.setText(_translate("MainWindow", "Hubs"))
        self.label_nodes.setText(_translate("MainWindow", "Nodes"))
        self.pushButton_run.setText(_translate("MainWindow", "RUN"))
        self.groupBox_initial_solution.setTitle(_translate("MainWindow", "Initial Solution"))
        self.groupBox_final_solution.setTitle(_translate("MainWindow", "Final Solution"))
        self.groupBox_result.setTitle(_translate("MainWindow", "Results"))
        self.groupBox_info_panel.setTitle(_translate("MainWindow", "Info Panel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menu_Export_As.setStatusTip(_translate("MainWindow", "Export As image."))
        self.menu_Export_As.setTitle(_translate("MainWindow", "Export As"))
        self.menuEdit.setStatusTip(_translate("MainWindow", "Edit"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menu_Clear.setStatusTip(_translate("MainWindow", "Clear Menu"))
        self.menu_Clear.setTitle(_translate("MainWindow", "Clear"))
        self.menuUndo.setTitle(_translate("MainWindow", "Undo"))
        self.menuRedo.setTitle(_translate("MainWindow", "Redo"))
        self.menu_Clustering.setTitle(_translate("MainWindow", "Clustering"))
        self.menu_Heuristic.setTitle(_translate("MainWindow", "Heuristic"))
        self.statusbar.setStatusTip(_translate("MainWindow", "Status Bar"))
        self.action_open_data.setText(_translate("MainWindow", "Open Data"))
        self.action_open_data.setStatusTip(_translate("MainWindow", "Open image."))
        self.action_open_data.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_save_initial_solution.setText(_translate("MainWindow", "Save Initial Solution"))
        self.action_save_initial_solution.setStatusTip(_translate("MainWindow", "Save the initial solution"))
        self.action_save_initial_solution.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.action_exit.setText(_translate("MainWindow", "Exit"))
        self.action_exit.setStatusTip(_translate("MainWindow", "Exit the app."))
        self.action_exit.setShortcut(_translate("MainWindow", "Shift+F4"))
        self.action_export_as_initial_solution.setText(_translate("MainWindow", "Initial Solution"))
        self.action_export_as_initial_solution.setStatusTip(_translate("MainWindow", "Export as Source"))
        self.action_export_as_initial_solution.setShortcut(_translate("MainWindow", "Ctrl+Shift+I"))
        self.action_export_as_final_solution.setText(_translate("MainWindow", "Final Solution"))
        self.action_export_as_final_solution.setStatusTip(_translate("MainWindow", "Export as Output"))
        self.action_export_as_final_solution.setShortcut(_translate("MainWindow", "Ctrl+Shift+O"))
        self.action_clear_initial_solution.setText(_translate("MainWindow", "Initial Solution"))
        self.action_clear_initial_solution.setStatusTip(_translate("MainWindow", "Clear the Initial Solution"))
        self.action_clear_initial_solution.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_clear_final_solution.setText(_translate("MainWindow", "Final Solution"))
        self.action_clear_final_solution.setStatusTip(_translate("MainWindow", "Clear the Final Solution"))
        self.action_clear_final_solution.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.action_k_means.setText(_translate("MainWindow", "K means"))
        self.action_k_means.setStatusTip(_translate("MainWindow", "Apply K mean"))
        self.action_k_means.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.action_affinity_propagation.setText(_translate("MainWindow", "Affinity Propagation"))
        self.action_affinity_propagation.setStatusTip(_translate("MainWindow", "Apply Affinity Propagation"))
        self.action_affinity_propagation.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.action_hill_climbing.setText(_translate("MainWindow", "Hill Climbing"))
        self.action_hill_climbing.setStatusTip(_translate("MainWindow", "Apply Hill Climbing"))
        self.action_hill_climbing.setShortcut(_translate("MainWindow", "Ctrl+Shift+H"))
        self.action_simulated_anneling.setText(_translate("MainWindow", "Simulated Anneling"))
        self.action_simulated_anneling.setStatusTip(_translate("MainWindow", "Apply Simulated Anneling"))
        self.action_simulated_anneling.setShortcut(_translate("MainWindow", "Ctrl+Shift+K"))
        self.action_save_final_solution.setText(_translate("MainWindow", "Save Final Solution"))
        self.action_save_final_solution.setStatusTip(_translate("MainWindow", "Save the Final Solution"))
        self.action_save_final_solution.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.action_undo_initial_solution.setText(_translate("MainWindow", "Initial Solution"))
        self.action_undo_initial_solution.setStatusTip(_translate("MainWindow", "Undo the Initial Solution"))
        self.action_undo_initial_solution.setShortcut(_translate("MainWindow", "Ctrl+Shift+R"))
        self.action_undo_final_solution.setText(_translate("MainWindow", "Final Solution"))
        self.action_undo_final_solution.setStatusTip(_translate("MainWindow", "Undo the Final Solution"))
        self.action_undo_final_solution.setShortcut(_translate("MainWindow", "Ctrl+Shift+F"))
        self.action_redo_initial_solution.setText(_translate("MainWindow", "Initial Solution"))
        self.action_redo_initial_solution.setStatusTip(_translate("MainWindow", "Redo the Initial Solution"))
        self.action_redo_initial_solution.setShortcut(_translate("MainWindow", "Ctrl+Shift+T"))
        self.action_redo_final_solution.setText(_translate("MainWindow", "Final Solution"))
        self.action_redo_final_solution.setStatusTip(_translate("MainWindow", "Redo the Final Solution"))
        self.action_redo_final_solution.setShortcut(_translate("MainWindow", "Ctrl+Shift+G"))
        self.action_mean_shift.setText(_translate("MainWindow", "Mean shift"))
        self.action_mean_shift.setStatusTip(_translate("MainWindow", "Apply mean shift "))
        self.action_mean_shift.setShortcut(_translate("MainWindow", "Ctrl+J"))
        self.action_spectral_clustering.setText(_translate("MainWindow", "Spectral Clustering"))
        self.action_spectral_clustering.setStatusTip(_translate("MainWindow", "Apply Spectral Clustering"))
        self.action_spectral_clustering.setShortcut(_translate("MainWindow", "Ctrl+K"))
        self.action_hierarcical_clustering.setText(_translate("MainWindow", "Hierarchical Clustering"))
        self.action_hierarcical_clustering.setStatusTip(_translate("MainWindow", "Apply Hierarchical clustering"))
        self.action_hierarcical_clustering.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.action_DBSCAN.setText(_translate("MainWindow", "DBSCAN"))
        self.action_DBSCAN.setStatusTip(_translate("MainWindow", "Apply DBSCAN "))
        self.action_DBSCAN.setShortcut(_translate("MainWindow", "Ctrl+Ş"))
